server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JulianCambraia/greeting-configuration
          #username: username
          #password: password
          default-label: main
          search-paths:
            'greeting-service*'
