server:
  port: 8100

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  config:
    import: optional:configserver:http://localhost:8761/
  cloud:
    config:
      profile: default
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: admin
    password: admin
  jackson:
    serialization:
      fail-on-empty-beans: false
    default-property-inclusion: non_null

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  retry:
    instances:
      foo-bar-retry:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  ratelimiter:
    instances:
      foo-bar-rate-limiter:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:
    instances:
      foo-bar-bulkhead:
        max-concurrent-calls: 15
springdoc:
  api-docs:
    path: book-service/v3/api-docs
  show-actuator: true
